import type {
  ExportOptions,
  PDFReportData,
  NormalizedPostAnalytics,
  NormalizedAccountAnalytics,
  WhiteLabelOptions,
} from '../../types/export'
import type { SocialPlatform, LocationData, RetentionPoint } from '../../types/social'
import { assertProAccess } from '../../middleware/roleGuard'
import type { PlanTier } from '../../types/social'

// ============================================
// PDF EXPORT SERVICE
// Generates professionally formatted PDF reports
// With optional white-label branding (PRO+ feature)
// ============================================

// Default ReGen brand colors
const DEFAULT_COLORS = {
  primary: '#6366F1', // Indigo
  secondary: '#8B5CF6', // Purple
  accent: '#EC4899', // Pink
  success: '#10B981', // Green
  warning: '#F59E0B', // Amber
  error: '#EF4444', // Red
  dark: '#1F2937', // Gray 800
  light: '#F9FAFB', // Gray 50
  text: '#111827', // Gray 900
  textSecondary: '#6B7280', // Gray 500
}

// Interface for resolved branding
interface BrandingConfig {
  companyName: string
  companyLogo?: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  footerText: string
  hideReGenBranding: boolean
  customCoverImage?: string
}

// Helper to get colors based on white-label settings
function getColors(whiteLabel?: WhiteLabelOptions) {
  if (!whiteLabel?.enabled) {
    return DEFAULT_COLORS
  }

  return {
    ...DEFAULT_COLORS,
    primary: whiteLabel.primaryColor || DEFAULT_COLORS.primary,
    secondary: whiteLabel.secondaryColor || DEFAULT_COLORS.secondary,
    accent: whiteLabel.accentColor || DEFAULT_COLORS.accent,
  }
}

// Helper to resolve branding config
function resolveBranding(whiteLabel?: WhiteLabelOptions): BrandingConfig {
  if (!whiteLabel?.enabled) {
    return {
      companyName: 'ReGen',
      primaryColor: DEFAULT_COLORS.primary,
      secondaryColor: DEFAULT_COLORS.secondary,
      accentColor: DEFAULT_COLORS.accent,
      footerText: 'Generated by ReGen • AI-Powered Social Media Analytics',
      hideReGenBranding: false,
    }
  }

  return {
    companyName: whiteLabel.companyName || 'ReGen',
    companyLogo: whiteLabel.companyLogo,
    primaryColor: whiteLabel.primaryColor || DEFAULT_COLORS.primary,
    secondaryColor: whiteLabel.secondaryColor || DEFAULT_COLORS.secondary,
    accentColor: whiteLabel.accentColor || DEFAULT_COLORS.accent,
    footerText: whiteLabel.footerText || `Generated by ${whiteLabel.companyName || 'ReGen'}`,
    hideReGenBranding: whiteLabel.hideReGenBranding || false,
    customCoverImage: whiteLabel.customCoverImage,
  }
}

// Current colors (will be set based on options)
let COLORS = { ...DEFAULT_COLORS }

// Page dimensions (A4)
const PAGE = {
  width: 595.28,
  height: 841.89,
  margin: 50,
  contentWidth: 595.28 - 100,
}

export interface PDFGenerationResult {
  buffer: Buffer
  fileName: string
  pageCount: number
  fileSize: number
}

export class PDFExportService {
  // ============================================
  // MAIN EXPORT METHOD
  // ============================================

  /**
   * Generate a professional PDF report
   * Note: This creates a structured HTML template that can be converted to PDF
   * using a library like puppeteer, playwright, or pdf-lib
   *
   * Supports white-label branding for PRO+ users
   */
  async generatePDFExport(
    userId: string,
    userPlan: PlanTier,
    options: ExportOptions,
    reportData: PDFReportData
  ): Promise<{
    html: string
    fileName: string
    estimatedPages: number
  }> {
    // Enforce PRO-only access
    assertProAccess(userPlan)

    // Resolve branding configuration
    const branding = resolveBranding(options.whiteLabel)

    // Update colors based on white-label settings
    COLORS = getColors(options.whiteLabel)

    const html = this.generateHTMLReport(reportData, options, branding)
    const fileName = this.generateFileName(userId, reportData, branding)
    const estimatedPages = this.estimatePageCount(reportData)

    return {
      html,
      fileName,
      estimatedPages,
    }
  }

  // ============================================
  // HTML REPORT GENERATION
  // ============================================

  /**
   * Generate complete HTML report for PDF conversion
   * Supports white-label branding
   */
  private generateHTMLReport(data: PDFReportData, options: ExportOptions, branding: BrandingConfig): string {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${branding.companyName} Analytics Report - ${data.reportTitle}</title>
  <style>
    ${this.getStyles(branding)}
  </style>
</head>
<body>
  <!-- Cover Page -->
  ${this.generateCoverPage(data, branding)}

  <!-- Summary Page -->
  <div class="page">
    ${this.generateSummarySection(data)}
  </div>

  <!-- Platform Analytics -->
  <div class="page">
    ${this.generatePlatformSection(data)}
  </div>

  <!-- Post Breakdown -->
  ${this.generatePostsSection(data)}

  <!-- Charts Section (if enabled) -->
  ${options.includeCharts ? this.generateChartsSection(data, branding) : ''}

  <!-- Location Analytics (PRO) -->
  ${options.includeLocationData && data.locationData ? this.generateLocationSection(data) : ''}

  <!-- Footer on each page -->
  ${this.generateFooterScript(data, branding)}
</body>
</html>
    `.trim()
  }

  // ============================================
  // PAGE SECTIONS
  // ============================================

  /**
   * Generate cover page with white-label support
   */
  private generateCoverPage(data: PDFReportData, branding: BrandingConfig): string {
    // Custom cover image background if provided
    const coverBgStyle = branding.customCoverImage
      ? `background-image: url('${branding.customCoverImage}'); background-size: cover; background-position: center;`
      : ''

    // Logo section - either custom logo or default text logo
    const logoSection = branding.companyLogo
      ? `
        <div class="logo-section">
          <img src="${branding.companyLogo}" alt="${branding.companyName}" class="custom-logo" />
        </div>
      `
      : `
        <div class="logo-section">
          <div class="logo">
            ${!branding.hideReGenBranding ? '<span class="logo-icon">✨</span>' : ''}
            <span class="logo-text">${this.escapeHtml(branding.companyName)}</span>
          </div>
          <div class="tagline">${branding.hideReGenBranding ? 'Social Media Analytics' : 'AI-Powered Social Media Analytics'}</div>
        </div>
      `

    return `
    <div class="page cover-page" style="${coverBgStyle}">
      <div class="cover-content">
        <!-- Logo and Branding -->
        ${logoSection}

        <!-- Report Title -->
        <div class="report-title-section">
          <h1 class="report-title">${this.escapeHtml(data.reportTitle)}</h1>
          <div class="report-subtitle">Analytics Report</div>
        </div>

        <!-- Creator Info -->
        <div class="creator-info">
          <div class="creator-name">${this.escapeHtml(data.creatorName)}</div>
          ${data.creatorEmail ? `<div class="creator-email">${this.escapeHtml(data.creatorEmail)}</div>` : ''}
        </div>

        <!-- Date Range -->
        <div class="date-range">
          <div class="date-label">Report Period</div>
          <div class="date-value">
            ${this.formatDate(data.dateRange.from)} — ${this.formatDate(data.dateRange.to)}
          </div>
        </div>

        <!-- Generation Info -->
        <div class="generated-info">
          Generated on ${this.formatDateTime(data.generatedAt)}
          ${!branding.hideReGenBranding ? '<br/><span class="powered-by">Powered by ReGen</span>' : ''}
        </div>
      </div>

      <div class="cover-decoration">
        <div class="decoration-circle circle-1"></div>
        <div class="decoration-circle circle-2"></div>
        <div class="decoration-circle circle-3"></div>
      </div>
    </div>
    `
  }

  /**
   * Generate summary section
   */
  private generateSummarySection(data: PDFReportData): string {
    const { summary } = data
    return `
    <div class="section">
      <h2 class="section-title">
        <span class="section-icon">📊</span>
        Performance Summary
      </h2>

      <div class="summary-grid">
        <div class="summary-card primary">
          <div class="summary-icon">👁️</div>
          <div class="summary-value">${this.formatNumber(summary.totalViews)}</div>
          <div class="summary-label">Total Views</div>
        </div>

        <div class="summary-card success">
          <div class="summary-icon">❤️</div>
          <div class="summary-value">${this.formatNumber(summary.totalEngagements)}</div>
          <div class="summary-label">Total Engagements</div>
        </div>

        <div class="summary-card accent">
          <div class="summary-icon">📈</div>
          <div class="summary-value">${summary.avgEngagementRate.toFixed(2)}%</div>
          <div class="summary-label">Avg Engagement Rate</div>
        </div>

        <div class="summary-card">
          <div class="summary-icon">📝</div>
          <div class="summary-value">${this.formatNumber(summary.totalPosts)}</div>
          <div class="summary-label">Total Posts</div>
        </div>
      </div>

      ${
        summary.topPerformingPlatform
          ? `
      <div class="highlight-box">
        <div class="highlight-icon">🏆</div>
        <div class="highlight-content">
          <div class="highlight-title">Top Performing Platform</div>
          <div class="highlight-value">${this.formatPlatformName(summary.topPerformingPlatform)}</div>
        </div>
      </div>
      `
          : ''
      }
    </div>
    `
  }

  /**
   * Generate platform analytics section
   */
  private generatePlatformSection(data: PDFReportData): string {
    if (!data.platformAnalytics || data.platformAnalytics.length === 0) {
      return ''
    }

    const platformRows = data.platformAnalytics
      .map(
        (platform) => `
      <tr>
        <td class="platform-cell">
          <span class="platform-icon">${this.getPlatformIcon(platform.platform)}</span>
          ${this.formatPlatformName(platform.platform)}
        </td>
        <td class="number-cell">${this.formatNumber(platform.followers)}</td>
        <td class="number-cell">${platform.posts}</td>
        <td class="number-cell">${this.formatNumber(platform.views)}</td>
        <td class="number-cell">${platform.engagementRate.toFixed(2)}%</td>
        <td class="number-cell">${this.formatNumber(platform.reach)}</td>
        <td class="growth-cell ${platform.growth >= 0 ? 'positive' : 'negative'}">
          ${platform.growth >= 0 ? '↑' : '↓'} ${Math.abs(platform.growth).toFixed(1)}%
        </td>
      </tr>
    `
      )
      .join('')

    return `
    <div class="section">
      <h2 class="section-title">
        <span class="section-icon">📱</span>
        Platform Performance
      </h2>

      <table class="data-table">
        <thead>
          <tr>
            <th>Platform</th>
            <th>Followers</th>
            <th>Posts</th>
            <th>Views</th>
            <th>Engagement</th>
            <th>Reach</th>
            <th>Growth</th>
          </tr>
        </thead>
        <tbody>
          ${platformRows}
        </tbody>
      </table>
    </div>
    `
  }

  /**
   * Generate posts breakdown section
   */
  private generatePostsSection(data: PDFReportData): string {
    if (!data.posts || data.posts.length === 0) {
      return ''
    }

    // Split into pages of 10 posts each
    const postsPerPage = 10
    const pages: string[] = []

    for (let i = 0; i < data.posts.length; i += postsPerPage) {
      const pagePosts = data.posts.slice(i, i + postsPerPage)
      const isFirstPage = i === 0

      const postRows = pagePosts
        .map(
          (post) => `
        <tr>
          <td class="platform-cell">
            <span class="platform-icon-small">${this.getPlatformIcon(post.platform)}</span>
          </td>
          <td class="title-cell">${this.escapeHtml(this.truncateText(post.title, 40))}</td>
          <td class="date-cell">${this.formatDate(post.publishedAt)}</td>
          <td class="number-cell">${this.formatNumber(post.analytics.views)}</td>
          <td class="number-cell">${this.formatNumber(post.analytics.likes)}</td>
          <td class="number-cell">${this.formatNumber(post.analytics.comments)}</td>
          <td class="number-cell">${this.formatNumber(post.analytics.shares)}</td>
          <td class="number-cell">${this.formatNumber(post.analytics.saves)}</td>
        </tr>
      `
        )
        .join('')

      pages.push(`
        <div class="page">
          <div class="section">
            ${
              isFirstPage
                ? `
            <h2 class="section-title">
              <span class="section-icon">📋</span>
              Post Performance Breakdown
            </h2>
            `
                : `
            <h3 class="section-subtitle">Post Performance (continued)</h3>
            `
            }

            <table class="data-table compact">
              <thead>
                <tr>
                  <th style="width: 40px;"></th>
                  <th>Title</th>
                  <th>Date</th>
                  <th>Views</th>
                  <th>Likes</th>
                  <th>Comments</th>
                  <th>Shares</th>
                  <th>Saves</th>
                </tr>
              </thead>
              <tbody>
                ${postRows}
              </tbody>
            </table>

            <div class="page-indicator">
              Showing posts ${i + 1}-${Math.min(i + postsPerPage, data.posts.length)} of ${data.posts.length}
            </div>
          </div>
        </div>
      `)
    }

    return pages.join('\n')
  }

  /**
   * Generate charts section (placeholder for chart rendering)
   * Uses branding colors for chart styling
   */
  private generateChartsSection(data: PDFReportData, branding: BrandingConfig): string {
    if (!data.chartsData) return ''

    return `
    <div class="page">
      <div class="section">
        <h2 class="section-title">
          <span class="section-icon">📈</span>
          Visual Analytics
        </h2>

        <!-- Views Over Time Chart -->
        ${
          data.chartsData.viewsOverTime && data.chartsData.viewsOverTime.length > 0
            ? `
        <div class="chart-container">
          <h3 class="chart-title">Views Over Time</h3>
          <div class="chart-placeholder" data-chart="viewsOverTime">
            ${this.renderSimpleBarChart(data.chartsData.viewsOverTime, 'views', branding)}
          </div>
        </div>
        `
            : ''
        }

        <!-- Engagement by Platform -->
        ${
          data.chartsData.engagementByPlatform && data.chartsData.engagementByPlatform.length > 0
            ? `
        <div class="chart-container">
          <h3 class="chart-title">Engagement by Platform</h3>
          <div class="chart-horizontal-bars">
            ${data.chartsData.engagementByPlatform
              .map(
                (item) => `
              <div class="horizontal-bar-row">
                <div class="bar-label">${item.platform}</div>
                <div class="bar-container">
                  <div class="bar-fill" style="width: ${Math.min(item.engagement * 5, 100)}%; background: linear-gradient(90deg, ${branding.primaryColor}, ${branding.secondaryColor});"></div>
                </div>
                <div class="bar-value">${item.engagement.toFixed(1)}%</div>
              </div>
            `
              )
              .join('')}
          </div>
        </div>
        `
            : ''
        }
      </div>
    </div>
    `
  }

  /**
   * Generate location section
   */
  private generateLocationSection(data: PDFReportData): string {
    if (!data.locationData || data.locationData.length === 0) return ''

    const locationRows = data.locationData
      .slice(0, 15)
      .map(
        (loc, index) => `
      <tr>
        <td class="rank-cell">#${index + 1}</td>
        <td class="location-cell">
          ${loc.city ? `${loc.city}, ` : ''}${loc.country}
        </td>
        <td class="number-cell">${loc.percentage.toFixed(1)}%</td>
        <td class="number-cell">${this.formatNumber(loc.engagement)}</td>
        <td class="bar-cell">
          <div class="inline-bar" style="width: ${Math.min(loc.percentage * 3, 100)}%"></div>
        </td>
      </tr>
    `
      )
      .join('')

    return `
    <div class="page">
      <div class="section">
        <h2 class="section-title">
          <span class="section-icon">🌍</span>
          Audience Location Analytics
        </h2>

        <table class="data-table">
          <thead>
            <tr>
              <th style="width: 50px;">Rank</th>
              <th>Location</th>
              <th>% of Audience</th>
              <th>Engagements</th>
              <th style="width: 150px;">Distribution</th>
            </tr>
          </thead>
          <tbody>
            ${locationRows}
          </tbody>
        </table>
      </div>
    </div>
    `
  }

  /**
   * Generate footer script for page numbering
   * Uses white-label footer text if configured
   */
  private generateFooterScript(data: PDFReportData, branding: BrandingConfig): string {
    const footerText = branding.hideReGenBranding
      ? `${branding.footerText} • ${this.formatDateTime(data.generatedAt)}`
      : `${branding.footerText} • ${this.formatDateTime(data.generatedAt)}`

    return `
    <script>
      // This script can be used by PDF generators to add page numbers
      window.reportMetadata = {
        title: '${this.escapeHtml(data.reportTitle)}',
        creator: '${this.escapeHtml(data.creatorName)}',
        generated: '${data.generatedAt.toISOString()}',
        footerText: '${footerText}',
        companyName: '${this.escapeHtml(branding.companyName)}',
        hideReGenBranding: ${branding.hideReGenBranding}
      };
    </script>
    `
  }

  // ============================================
  // STYLES
  // ============================================

  private getStyles(branding: BrandingConfig): string {
    // Use branding colors for the styles
    const colors = {
      ...DEFAULT_COLORS,
      primary: branding.primaryColor,
      secondary: branding.secondaryColor,
      accent: branding.accentColor,
    }

    return `
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }

      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
        font-size: 12px;
        line-height: 1.5;
        color: ${colors.text};
        background: white;
      }

      /* Custom logo styles for white-label */
      .custom-logo {
        max-width: 200px;
        max-height: 80px;
        object-fit: contain;
        margin-bottom: 20px;
      }

      .powered-by {
        font-size: 10px;
        opacity: 0.7;
      }

      .page {
        width: 210mm;
        min-height: 297mm;
        padding: 20mm;
        margin: 0 auto;
        background: white;
        page-break-after: always;
      }

      .page:last-child {
        page-break-after: auto;
      }

      /* Cover Page */
      .cover-page {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
        position: relative;
        overflow: hidden;
      }

      .cover-content {
        position: relative;
        z-index: 2;
      }

      .logo-section {
        margin-bottom: 60px;
      }

      .logo {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 12px;
        margin-bottom: 8px;
      }

      .logo-icon {
        font-size: 48px;
      }

      .logo-text {
        font-size: 48px;
        font-weight: 700;
        background: linear-gradient(135deg, ${COLORS.primary}, ${COLORS.secondary});
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
      }

      .tagline {
        font-size: 14px;
        color: ${COLORS.textSecondary};
        letter-spacing: 2px;
        text-transform: uppercase;
      }

      .report-title-section {
        margin-bottom: 40px;
      }

      .report-title {
        font-size: 32px;
        font-weight: 700;
        color: ${COLORS.text};
        margin-bottom: 8px;
      }

      .report-subtitle {
        font-size: 18px;
        color: ${COLORS.textSecondary};
      }

      .creator-info {
        margin-bottom: 30px;
      }

      .creator-name {
        font-size: 20px;
        font-weight: 600;
        color: ${COLORS.text};
      }

      .creator-email {
        font-size: 14px;
        color: ${COLORS.textSecondary};
      }

      .date-range {
        margin-bottom: 40px;
        padding: 20px 40px;
        background: ${COLORS.light};
        border-radius: 12px;
      }

      .date-label {
        font-size: 12px;
        color: ${COLORS.textSecondary};
        text-transform: uppercase;
        letter-spacing: 1px;
        margin-bottom: 4px;
      }

      .date-value {
        font-size: 18px;
        font-weight: 600;
        color: ${COLORS.primary};
      }

      .generated-info {
        font-size: 11px;
        color: ${COLORS.textSecondary};
      }

      .cover-decoration {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        overflow: hidden;
        z-index: 1;
      }

      .decoration-circle {
        position: absolute;
        border-radius: 50%;
        opacity: 0.1;
      }

      .circle-1 {
        width: 400px;
        height: 400px;
        background: ${COLORS.primary};
        top: -150px;
        right: -100px;
      }

      .circle-2 {
        width: 300px;
        height: 300px;
        background: ${COLORS.secondary};
        bottom: -100px;
        left: -100px;
      }

      .circle-3 {
        width: 200px;
        height: 200px;
        background: ${COLORS.accent};
        bottom: 100px;
        right: -50px;
      }

      /* Section Styles */
      .section {
        margin-bottom: 30px;
      }

      .section-title {
        display: flex;
        align-items: center;
        gap: 12px;
        font-size: 20px;
        font-weight: 700;
        color: ${COLORS.text};
        margin-bottom: 20px;
        padding-bottom: 10px;
        border-bottom: 2px solid ${COLORS.light};
      }

      .section-icon {
        font-size: 24px;
      }

      .section-subtitle {
        font-size: 16px;
        font-weight: 600;
        color: ${COLORS.textSecondary};
        margin-bottom: 15px;
      }

      /* Summary Grid */
      .summary-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 15px;
        margin-bottom: 20px;
      }

      .summary-card {
        padding: 20px;
        background: ${COLORS.light};
        border-radius: 12px;
        text-align: center;
      }

      .summary-card.primary {
        background: linear-gradient(135deg, ${COLORS.primary}15, ${COLORS.primary}25);
        border: 1px solid ${COLORS.primary}30;
      }

      .summary-card.success {
        background: linear-gradient(135deg, ${COLORS.success}15, ${COLORS.success}25);
        border: 1px solid ${COLORS.success}30;
      }

      .summary-card.accent {
        background: linear-gradient(135deg, ${COLORS.accent}15, ${COLORS.accent}25);
        border: 1px solid ${COLORS.accent}30;
      }

      .summary-icon {
        font-size: 28px;
        margin-bottom: 8px;
      }

      .summary-value {
        font-size: 28px;
        font-weight: 700;
        color: ${COLORS.text};
        margin-bottom: 4px;
      }

      .summary-label {
        font-size: 12px;
        color: ${COLORS.textSecondary};
        text-transform: uppercase;
        letter-spacing: 0.5px;
      }

      /* Highlight Box */
      .highlight-box {
        display: flex;
        align-items: center;
        gap: 15px;
        padding: 20px;
        background: linear-gradient(135deg, ${COLORS.primary}, ${COLORS.secondary});
        border-radius: 12px;
        color: white;
      }

      .highlight-icon {
        font-size: 36px;
      }

      .highlight-title {
        font-size: 12px;
        opacity: 0.9;
        margin-bottom: 4px;
      }

      .highlight-value {
        font-size: 20px;
        font-weight: 700;
      }

      /* Data Tables */
      .data-table {
        width: 100%;
        border-collapse: collapse;
        font-size: 11px;
      }

      .data-table th {
        background: ${COLORS.light};
        padding: 12px 10px;
        text-align: left;
        font-weight: 600;
        color: ${COLORS.textSecondary};
        text-transform: uppercase;
        letter-spacing: 0.5px;
        font-size: 10px;
        border-bottom: 2px solid #e5e7eb;
      }

      .data-table td {
        padding: 12px 10px;
        border-bottom: 1px solid #f3f4f6;
      }

      .data-table tr:hover {
        background: ${COLORS.light};
      }

      .data-table.compact td {
        padding: 8px 10px;
      }

      .platform-cell {
        display: flex;
        align-items: center;
        gap: 8px;
        font-weight: 500;
      }

      .platform-icon {
        font-size: 18px;
      }

      .platform-icon-small {
        font-size: 14px;
      }

      .number-cell {
        text-align: right;
        font-variant-numeric: tabular-nums;
      }

      .date-cell {
        color: ${COLORS.textSecondary};
      }

      .title-cell {
        max-width: 200px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }

      .growth-cell {
        text-align: right;
        font-weight: 600;
      }

      .growth-cell.positive {
        color: ${COLORS.success};
      }

      .growth-cell.negative {
        color: ${COLORS.error};
      }

      .rank-cell {
        font-weight: 600;
        color: ${COLORS.textSecondary};
      }

      .bar-cell {
        padding: 12px 10px;
      }

      .inline-bar {
        height: 8px;
        background: linear-gradient(90deg, ${COLORS.primary}, ${COLORS.secondary});
        border-radius: 4px;
      }

      /* Chart Styles */
      .chart-container {
        margin-bottom: 30px;
        padding: 20px;
        background: ${COLORS.light};
        border-radius: 12px;
      }

      .chart-title {
        font-size: 14px;
        font-weight: 600;
        color: ${COLORS.text};
        margin-bottom: 15px;
      }

      .chart-placeholder {
        min-height: 150px;
      }

      .chart-horizontal-bars {
        display: flex;
        flex-direction: column;
        gap: 12px;
      }

      .horizontal-bar-row {
        display: flex;
        align-items: center;
        gap: 10px;
      }

      .bar-label {
        width: 80px;
        font-size: 11px;
        font-weight: 500;
      }

      .bar-container {
        flex: 1;
        height: 20px;
        background: #e5e7eb;
        border-radius: 10px;
        overflow: hidden;
      }

      .bar-fill {
        height: 100%;
        background: linear-gradient(90deg, ${COLORS.primary}, ${COLORS.secondary});
        border-radius: 10px;
        transition: width 0.3s ease;
      }

      .bar-value {
        width: 50px;
        font-size: 11px;
        font-weight: 600;
        text-align: right;
      }

      /* Page Indicator */
      .page-indicator {
        margin-top: 15px;
        text-align: center;
        font-size: 10px;
        color: ${COLORS.textSecondary};
      }

      /* Print Styles */
      @media print {
        body {
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }

        .page {
          page-break-after: always;
          margin: 0;
        }
      }

      @page {
        size: A4;
        margin: 0;
      }
    `
  }

  // ============================================
  // HELPER METHODS
  // ============================================

  private escapeHtml(text: string): string {
    const div = { innerHTML: '' }
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;')
  }

  private formatDate(date: Date | string): string {
    const d = typeof date === 'string' ? new Date(date) : date
    return d.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    })
  }

  private formatDateTime(date: Date): string {
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  private formatNumber(num: number): string {
    if (num >= 1000000) {
      return (num / 1000000).toFixed(1) + 'M'
    }
    if (num >= 1000) {
      return (num / 1000).toFixed(1) + 'K'
    }
    return num.toLocaleString()
  }

  private truncateText(text: string, maxLength: number): string {
    if (text.length <= maxLength) return text
    return text.substring(0, maxLength - 3) + '...'
  }

  private formatPlatformName(platform: SocialPlatform): string {
    const names: Record<SocialPlatform, string> = {
      instagram: 'Instagram',
      tiktok: 'TikTok',
      youtube: 'YouTube',
      twitter: 'Twitter/X',
      linkedin: 'LinkedIn',
      facebook: 'Facebook',
      snapchat: 'Snapchat',
    }
    return names[platform] || platform
  }

  private getPlatformIcon(platform: SocialPlatform): string {
    const icons: Record<SocialPlatform, string> = {
      instagram: '📸',
      tiktok: '🎵',
      youtube: '🎬',
      twitter: '🐦',
      linkedin: '💼',
      facebook: '👤',
      snapchat: '👻',
    }
    return icons[platform] || '📱'
  }

  private generateFileName(userId: string, data: PDFReportData, branding?: BrandingConfig): string {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').substring(0, 19)
    const creatorSlug = data.creatorName.toLowerCase().replace(/[^a-z0-9]/g, '_').substring(0, 20)

    // Use company name for white-label exports, otherwise use ReGen
    const prefix = branding?.hideReGenBranding && branding.companyName !== 'ReGen'
      ? branding.companyName.toLowerCase().replace(/[^a-z0-9]/g, '_').substring(0, 15)
      : 'regen'

    return `${prefix}_report_${creatorSlug}_${timestamp}.pdf`
  }

  private estimatePageCount(data: PDFReportData): number {
    let pages = 2 // Cover + Summary
    pages += 1 // Platform analytics
    pages += Math.ceil((data.posts?.length || 0) / 10) // Posts (10 per page)
    if (data.chartsData) pages += 1
    if (data.locationData?.length) pages += 1
    return pages
  }

  private renderSimpleBarChart(
    data: Array<{ date: string; views: number }>,
    valueKey: string,
    branding?: BrandingConfig
  ): string {
    if (!data.length) return ''

    const maxValue = Math.max(...data.map((d) => d.views))
    const barWidth = Math.floor(450 / data.length) - 2

    // Use branding colors if provided
    const primaryColor = branding?.primaryColor || DEFAULT_COLORS.primary
    const secondaryColor = branding?.secondaryColor || DEFAULT_COLORS.secondary

    return `
      <div style="display: flex; align-items: flex-end; height: 120px; gap: 2px; padding: 10px 0;">
        ${data
          .slice(0, 30)
          .map(
            (d) => `
          <div style="
            width: ${barWidth}px;
            height: ${Math.max((d.views / maxValue) * 100, 2)}%;
            background: linear-gradient(to top, ${primaryColor}, ${secondaryColor});
            border-radius: 2px 2px 0 0;
          " title="${d.date}: ${this.formatNumber(d.views)}"></div>
        `
          )
          .join('')}
      </div>
    `
  }
}

// Singleton instance
export const pdfExportService = new PDFExportService()
